In [49]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [ ]:
df = pd.read_csv('/qcew-2023-2025q2.csv')
filter = df['Industry Name'].str.contains('care', case=False, na=False)
df['Industry Name'][filter].groupby(df['Industry Name']).count()

Industry Name
All Other Ambulatory Health Care Svc             315
All Other Health and Personal Care Retailers     351
All Other Outpatient Care Centers                604
Ambulatory Health Care Services                 1367
Child Day Care Services                         3024
Community Care Facility for the Elderly         1308
Continuing Care Retirement Communities           370
Death Care Services                             1115
Hair, Nail, and Skin Care Services               480
Health Care and Social Assistance               1998
Health and Personal Care Retailers              1372
Home Health Care Services                       1650
Miscellaneous Ambulatory Health Care Svc         249
Nursing Care Facilities                         1893
Nursing and Residential Care Facilities          638
Other Ambulatory Health Care Services            520
Other Health and Personal Care Retailers         369
Other Outpatient Care Centers                    783
Other Personal Care Services                     729
Other Residential Care Facilities               1050
Outpatient Care Centers                          867
Personal Care Services                           588
Pet Care (except Veterinary) Services            956
Residental Mental & Substance Abuse Care         942
Name: Industry Name, dtype: int64

In [ ]:
acceptable = ['Home Health Care Services', 'Other Health and Personal Care Retailers', 'Other Outpatient Care Centers', 'Other Personal Care Services', 'Outpatient Care Centers', 'Personal Care Services']

new_df = df[df['Industry Name'].isin(acceptable)]
new_df

,Area Type,Area Name,Year,Time Period,Ownership,NAICS Level,NAICS Code,Industry Name,Establishments,Average Monthly Employment,1st Month Emp,2nd Month Emp,3rd Month Emp,Total Wages (All Workers),Average Weekly Wages
115,County,Alameda County,2023,1st Qtr,Private,5,81219,Other Personal Care Services,157,976,939,977,1013,7834413.0,617
160,County,Alameda County,2023,1st Qtr,Private,5,62161,Home Health Care Services,185,4523,4450,4578,4541,74456534.0,1266
353,County,Alameda County,2023,1st Qtr,Private,5,45619,Other Health and Personal Care Retailers,78,328,327,332,327,5120802.0,1199
749,County,Alameda County,2023,1st Qtr,Local Government,4,6214,Outpatient Care Centers,1,55,55,54,56,1391010.0,1945
785,County,Alameda County,2023,1st Qtr,Private,4,6214,Outpatient Care Centers,299,20084,19973,20080,20201,682751196.0,2615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699006,County,Yolo County,2025,2nd Qtr,Private,4,6214,Outpatient Care Centers,37,0,1070,1070,1066,22552019.0,1623
699721,County,Yuba County,2025,2nd Qtr,Private,4,8121,Personal Care Services,8,0,31,30,33,238868.0,586
699763,County,Yuba County,2025,2nd Qtr,Local Government,4,6214,Outpatient Care Centers,1,0,22,22,22,573667.0,2006
699764,County,Yuba County,2025,2nd Qtr,Private,4,6214,Outpatient Care Centers,16,0,335,338,336,6708711.0,1534
699768,County,Yuba County,2025,2nd Qtr,Private,5,62149,Other Outpatient Care Centers,11,0,291,296,294,6079990.0,1593

In [116]:
df2 = pd.read_csv('/data_gov_lse_rexus.csv', on_bad_lines='skip')
df2

,Lease Number,Current Expiration Date,Lease Initial Effective Date,Location Code,Lease ANSI Rentable Sqft,Lease Usable Sqft,Lse Structured Parking Spaces,Lse Surface Parking Spaces,Lease Annual Rent Amount,Lease Responsibility,Lessor Name,Lessor In-Care-Of,Lessor Address 1,Lessor Address 2,Lessor Country,Lessor State,Lessor Zip Code,Lessor County,Lessor City
0,LCT00579,30-Sep-2027,01-Oct-2022,CT0047,269.0,269.0,0,0,3453.84,LESSOR,UNITED STATES POSTAL SERVICE,Roger Nord,2825 Lone Oak Pkwy,NaN,US,MN,551211551,,Saint Paul
1,LCT04970,31-Dec-2027,01-Jan-2018,CT3316,41105.0,37395.0,0,164,1001089.95,LESSOR,BAKER PROPERTIES LIMITED PARTNERSHIP,DonaldDuthaler Jr.,4 W Red Oak Ln,STE 109,US,NY,106043603,,WHITE PLAINS
2,LCT04610,31-May-2028,01-Jun-2013,CT3319,5773.0,5020.0,1,7,205576.95,LESSOR,LANDMARK SQUARE 1-6 LLC,Lori Micale,1 VANDERBILT AVE FL 28,NaN,US,NY,100173807,,NEW YORK
3,LCT04939,31-Aug-2029,01-Sep-2014,CT3323,17328.0,15150.0,0,0,444748.68,LESSOR,AEF REALTY LLC,larry michaud,333 E RIVER DR,NaN,US,CT,061084200,,EAST HARTFORD
4,LCT00411,14-Aug-2037,15-Aug-2022,CT3331,58601.0,51859.0,18,0,2503618.47,LESSOR,"157 CHURCH,LLC",Cheryl Chase,157 Church St,NaN,US,CT,065102100,,New Haven
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7385,LNV02965,23-Sep-2027,24-Sep-2012,NV8371,27219.0,23669.0,4,20,878161.56,LESSOR,MRK AIRPORT LLC,Robin S Suo,845 UNITED NATIONS PLZ,APT 42B,US,NY,100173534,,NEW YORK
7386,LNV03218,31-Oct-2028,01-Aug-2013,NV8403,11074.0,10894.0,0,7,500965.00,LESSOR,KTR LV IV LLC,Mathias Hughes,4545 Airport Way,NaN,US,CO,802395716,,Denver
7387,LNV03308,06-Mar-2037,07-Mar-2017,NV8446,35839.0,35839.0,0,221,741123.11,LESSOR,1984 LEVIN LIVING TRUST DATED,MARTIN EISENBERG,655 SKYWAY RD.,STE 110,US,CA,940702710,,SAN CARLOS
7388,LNV03231,07-Mar-2037,08-Mar-2017,NV8447,34560.0,34050.0,0,288,528926.47,LESSOR,BLM NEVADA LTD,Samantha Cadenhead,5300 SEATON LN,NaN,US,WY,830145239,,WILSON
7389,LNV00656,30-Jun-2027,01-Jul-2020,NV8464,13366.0,11583.0,40,0,544683.01,LESSOR,"BRE/HC LAS VEGAS MASTER HOLDINGS,L.L.C.",Lisa Salvio,3800 HOWARD HUGHES PKWY STE 140,NaN,US,NV,891695913,,LAS VEGAS

In [ ]:
gdf = gpd.read_file('/Fair_Market_Rents.shp')
gdf

,OBJECTID,FMR_0BDR,FMR_1BDR,FMR_2BDR,FMR_3BDR,FMR_4BDR,FMR_AREANA,FMR_CODE,SHAPE_Leng,SHAPE_Area,geometry
0,1,404.0,406.0,485.0,643.0,646.0,"Guayama, PR MSA",METRO25020M25020,1.310913,0.028181,"MULTIPOLYGON (((-66.21312 17.92287, -66.21305 ..."
1,2,410.0,421.0,473.0,628.0,630.0,"Yauco, PR MSA",METRO49500M49500,1.827205,0.042532,"MULTIPOLYGON (((-66.9719 17.92988, -66.97266 1..."
2,3,410.0,421.0,473.0,667.0,737.0,Puerto Rico HUD Nonmetro Area,NCNTY72923N72923,5.127892,0.072106,"MULTIPOLYGON (((-66.24508 17.91583, -66.24534 ..."
3,4,423.0,425.0,520.0,669.0,717.0,"San German, PR MSA",METRO41900M41900,2.088802,0.049395,"MULTIPOLYGON (((-66.98525 17.95013, -66.98415 ..."
4,5,450.0,453.0,519.0,632.0,713.0,"Aguadilla-Isabela, PR MSA",METRO10380M10380,2.658926,0.105064,"POLYGON ((-67.08068 18.51357, -67.07901 18.513..."
...,...,...,...,...,...,...,...,...,...,...,...
2597,2598,2330.0,2651.0,2994.0,3996.0,4528.0,"Santa Maria-Santa Barbara, CA MSA",METRO42200M42200,7.045416,0.700491,"MULTIPOLYGON (((-119.04635 33.4651, -119.04668..."
2598,2599,2340.0,2367.0,2879.0,3990.0,4400.0,"Salinas, CA MSA",METRO41500M41500,6.433055,0.860395,"MULTIPOLYGON (((-121.45301 35.87489, -121.4536..."
2599,2600,2383.0,2694.0,3132.0,4011.0,4425.0,"San Jose-Sunnyvale-Santa Clara, CA HUD Metro F...",METRO41940M41940,3.873784,0.341465,"MULTIPOLYGON (((-122.09391 37.45439, -122.0941..."
2600,2601,2386.0,2451.0,2752.0,3434.0,3700.0,"New York, NY HUD Metro FMR Area",METRO35620MM5600,9.441001,0.201632,"MULTIPOLYGON (((-74.20194 40.5737, -74.20355 4..."
2601,2602,2849.0,3085.0,4054.0,5000.0,5504.0,"Santa Cruz-Watsonville, CA MSA",METRO42100M42100,2.352754,0.117202,"POLYGON ((-122.15056 37.27596, -122.15054 37.2..."

In [128]:
df2['Lessor State'] = df2['Lessor State'].replace('Illinois', 'IL')

states_raw = df2
filter1 = states_raw['Lessor Country'] == 'US'

states_no_ca = states_raw[filter1]
states_no_ca.describe(include='all')
filter2 = states_no_ca['Lessor State'].isna()

states_us = states_no_ca[~filter2]
states_us

,Lease Number,Current Expiration Date,Lease Initial Effective Date,Location Code,Lease ANSI Rentable Sqft,Lease Usable Sqft,Lse Structured Parking Spaces,Lse Surface Parking Spaces,Lease Annual Rent Amount,Lease Responsibility,Lessor Name,Lessor In-Care-Of,Lessor Address 1,Lessor Address 2,Lessor Country,Lessor State,Lessor Zip Code,Lessor County,Lessor City
0,LCT00579,30-Sep-2027,01-Oct-2022,CT0047,269.0,269.0,0,0,3453.84,LESSOR,UNITED STATES POSTAL SERVICE,Roger Nord,2825 Lone Oak Pkwy,NaN,US,MN,551211551,,Saint Paul
1,LCT04970,31-Dec-2027,01-Jan-2018,CT3316,41105.0,37395.0,0,164,1001089.95,LESSOR,BAKER PROPERTIES LIMITED PARTNERSHIP,DonaldDuthaler Jr.,4 W Red Oak Ln,STE 109,US,NY,106043603,,WHITE PLAINS
2,LCT04610,31-May-2028,01-Jun-2013,CT3319,5773.0,5020.0,1,7,205576.95,LESSOR,LANDMARK SQUARE 1-6 LLC,Lori Micale,1 VANDERBILT AVE FL 28,NaN,US,NY,100173807,,NEW YORK
3,LCT04939,31-Aug-2029,01-Sep-2014,CT3323,17328.0,15150.0,0,0,444748.68,LESSOR,AEF REALTY LLC,larry michaud,333 E RIVER DR,NaN,US,CT,061084200,,EAST HARTFORD
4,LCT00411,14-Aug-2037,15-Aug-2022,CT3331,58601.0,51859.0,18,0,2503618.47,LESSOR,"157 CHURCH,LLC",Cheryl Chase,157 Church St,NaN,US,CT,065102100,,New Haven
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7385,LNV02965,23-Sep-2027,24-Sep-2012,NV8371,27219.0,23669.0,4,20,878161.56,LESSOR,MRK AIRPORT LLC,Robin S Suo,845 UNITED NATIONS PLZ,APT 42B,US,NY,100173534,,NEW YORK
7386,LNV03218,31-Oct-2028,01-Aug-2013,NV8403,11074.0,10894.0,0,7,500965.00,LESSOR,KTR LV IV LLC,Mathias Hughes,4545 Airport Way,NaN,US,CO,802395716,,Denver
7387,LNV03308,06-Mar-2037,07-Mar-2017,NV8446,35839.0,35839.0,0,221,741123.11,LESSOR,1984 LEVIN LIVING TRUST DATED,MARTIN EISENBERG,655 SKYWAY RD.,STE 110,US,CA,940702710,,SAN CARLOS
7388,LNV03231,07-Mar-2037,08-Mar-2017,NV8447,34560.0,34050.0,0,288,528926.47,LESSOR,BLM NEVADA LTD,Samantha Cadenhead,5300 SEATON LN,NaN,US,WY,830145239,,WILSON
7389,LNV00656,30-Jun-2027,01-Jul-2020,NV8464,13366.0,11583.0,40,0,544683.01,LESSOR,"BRE/HC LAS VEGAS MASTER HOLDINGS,L.L.C.",Lisa Salvio,3800 HOWARD HUGHES PKWY STE 140,NaN,US,NV,891695913,,LAS VEGAS

In [129]:
df = pd.read_csv('data_gov_bldg_rexus.csv')
zip_to_county = df[['Bldg County', 'Bldg Zip']]

df2['Lessor Zip Code'] = df2['Lessor Zip Code'].astype(str)
zip_to_county['Bldg Zip'] = zip_to_county['Bldg Zip'].astype(str)

merged = df2.merge(zip_to_county, left_on='Lessor Zip Code', right_on='Bldg Zip')

just_what_i_want = merged.loc[:, ['Bldg County', 'Lease Annual Rent Amount', 'Lease ANSI Rentable Sqft']]
just_what_i_want.describe()

states = states_us.loc[:, ['Lessor State', 'Lease Annual Rent Amount', 'Lease ANSI Rentable Sqft']]

avg = just_what_i_want.groupby('Bldg County').mean()
state_avg = states.groupby('Lessor State').mean()

avg['Average Rent per Sqft'] = avg['Lease Annual Rent Amount'] / avg['Lease ANSI Rentable Sqft'].replace(0, np.nan)
state_avg['Average Rent per Sqft'] = state_avg['Lease Annual Rent Amount'] / state_avg['Lease ANSI Rentable Sqft'].replace(0, np.nan)
avg.to_csv('Lease_cost_by_county.csv')
state_avg.to_csv('Lease_cost_by_state.csv')

/tmp/ipykernel_498/2977836955.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zip_to_county['Bldg Zip'] = zip_to_county['Bldg Zip'].astype(str)